ATOM    : /[0-9]+/
NOP     : "+" | "*"
UOP     : "-"
lambda  : "(" "lam" "(" IDE ")" "=>" "{" expr "}" ")" expr
op      : UOP expr | NOP "(" (expr + ",")* expr ")"
IDE     : WORD
SYM     : IDE

expr    : ATOM | op | lambda | SYM | "(" + expr + ")"

start   : expr

%import common.WORD   // imports from terminal library
%ignore " "           // Disregard spaces in text
%ignore "\n"           // Disregard spaces in text
