INTEGER     : /[0-9]+/
NOP         : "+" | "*" | "/" | "=" | ">" | ">=" | "<" | "<=" | "&" | "^" | "@" | "elem"
UOP         : "-" | "!" | "empty"
IDE         : /(?!(true|false|lam|if|then|else|elem|empty)\b)[a-z_][a-z0-9_]*/i
SYM         : IDE
IN          : ";" 
BOOL        : "true" | "false"
ELLIPSIS    : "..." IDE

anonfun     : "lam" "(" IDE ")" "=>" "{" expr "}"
list        : "[" (expr ("," expr)*)? "]"
tuple       : "(" (expr ("," expr)*)? ")"
atom        : INTEGER | anonfun | BOOL | list | tuple
expr_app    : expr expr
lambda      : "lam" "(" IDE ")" "=>" "{" expr "}"
lambda_app  : lambda expr
op          : UOP expr | NOP "(" (expr + ",")* expr ")"
decl        : SYM ":=" expr
list_pattern: "[" (IDE ("," IDE)*)? ("," ELLIPSIS)? "]"
letin       : decl IN expr
unpack      : list_pattern "<-" expr IN expr
conditional :  "if" expr "then" expr "else" expr
expr        : conditional | atom | op | lambda_app | expr_app | SYM | "(" + expr + ")" | letin | unpack

start       : expr

%import common.WORD   // imports from terminal library
%ignore " "           // Disregard spaces in text
%ignore "\n"           // Disregard spaces in text

COMMENT : /\/\// /.*/
        | /\/\*/ /.*/ /\*\//

%ignore COMMENT
